### PR TITLE
#45-Add repo link to header

### PR DESCRIPTION
**Pull request by katetaylormoz**

### CODE REVIEW

**Comment by misslivirose** [comment]
This is already in the footer - given how small the pages are, does it need to be in both places? If we think it should be a header link, should we remove it from the footer?

**Comment by katetaylormoz** [comment]
The footer brings you to the Ocho directory rather than the MemoryCache specific space. The thinking was that this would increase exposure to the Wiki and Discussions sections

**Comment by katetaylormoz** [comment]
...Which makes me think... 

Should it say 'Docs' instead and then link to the Wiki?

**Comment by misslivirose** [comment]
Ah, got it! I think that linking to "Docs" there would be a good idea if we're going directly to the wiki. I can also look at whether we can make the footer link directly to this repo instead of the org.

**Comment by katetaylormoz** [comment]
I think the Ocho Repository makes sense in the footer along with the messaging -- it gives context as to where the project 'lives'. The repository is linked in the About Page, which makes sense as well contextually, because it's primarily dev-focused at this point in time

I like 'Docs' in the header because it gives us space to grow and the documentation can then be designed so people can find what they are looking for

**Review by misslivirose — CHANGES_REQUESTED** [review]
Per issue discussion, update to have this read "Docs" and point to https://github.com/Mozilla-Ocho/Memory-Cache/wiki

**Review by misslivirose — APPROVED** [review]

**Pull request merged**
